### ISSUE TITLE
failed to run

### ISSUE THREAD

**Issue by MinzChan** [ouhenio/text-guided-diffusion-style-transfer#12]
E:\Project\Github\text-guided-diffusion-style-transfer-main\venv\Scripts\python.exe E:/Project/Github/text-guided-diffusion-style-transfer-main/main.py
100%|███████████████████████████████████████| 335M/335M [00:33<00:00, 10.6MiB/s]
E:\Project\Github\text-guided-diffusion-style-transfer-main\venv\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
E:\Project\Github\text-guided-diffusion-style-transfer-main\venv\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG19_Weights.IMAGENET1K_V1`. You can also use `weights=VGG19_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Pretrained model is successfully loaded
0it [00:00, ?it/s]
  0%|          | 0/25 [00:15<?, ?it/s]
0it [00:15, ?it/s]
Traceback (most recent call last):
  File "E:/Project/Github/text-guided-diffusion-style-transfer-main/main.py", line 237, in <module>
    for j, sample in tqdm.tqdm(enumerate(samples)):
  File "E:\Project\Github\text-guided-diffusion-style-transfer-main\venv\lib\site-packages\tqdm\std.py", line 1178, in __iter__
    for obj in iterable:
  File "E:\Project\Github\text-guided-diffusion-style-transfer-main\guided-diffusion\guided_diffusion\gaussian_diffusion.py", line 637, in p_sample_loop_progressive
    out = sample_fn(
  File "E:\Project\Github\text-guided-diffusion-style-transfer-main\guided-diffusion\guided_diffusion\gaussian_diffusion.py", line 461, in p_sample
    out = self.p_mean_variance(
  File "E:\Project\Github\text-guided-diffusion-style-transfer-main\guided-diffusion\guided_diffusion\respace.py", line 91, in p_mean_variance
    return super().p_mean_variance(self._wrap_model(model), *args, **kwargs)
  File "E:\Project\Github\text-guided-diffusion-style-transfer-main\guided-diffusion\guided_diffusion\gaussian_diffusion.py", line 260, in p_mean_variance
    model_output = model(x, self._scale_timesteps(t), **model_kwargs)
  File "E:\Project\Github\text-guided-diffusion-style-transfer-main\guided-diffusion\guided_diffusion\respace.py", line 128, in __call__
    return self.model(x, new_ts, **kwargs)
  File "E:\Project\Github\text-guided-diffusion-style-transfer-main\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Project\Github\text-guided-diffusion-style-transfer-main\guided-diffusion\guided_diffusion\unet.py", line 656, in forward
    h = module(h, emb)
  File "E:\Project\Github\text-guided-diffusion-style-transfer-main\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Project\Github\text-guided-diffusion-style-transfer-main\guided-diffusion\guided_diffusion\unet.py", line 77, in forward
    x = layer(x)
  File "E:\Project\Github\text-guided-diffusion-style-transfer-main\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Project\Github\text-guided-diffusion-style-transfer-main\venv\lib\site-packages\torch\nn\modules\conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "E:\Project\Github\text-guided-diffusion-style-transfer-main\venv\lib\site-packages\torch\nn\modules\conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'

Process finished with exit code 1

**Comment by ouhenio** [comment]
Hi @MinzChan.

I just reinstalled the entire repo from zero, but I can't seem to reproduce your error. Did you use `main.py` as it is, or edited something in it? Could you share with me please the version of the libraries in your python environment.
